const char ippteststr[] =
"# ippFile API test file\n"
"\n"
"# DEFINE\n"
"DEFINE width 21000\n"
"DEFINE length 29700\n"
"DEFINE-DEFAULT color white\n"
"\n"
"# GROUP + ATTR + MEMBER\n"
"GROUP operation-attributes-tag\n"
"ATTR charset attributes-charset \"utf-8\"\n"
"ATTR naturalLanguage attributes-natural-language en\n"
"ATTR name job-name \"Test Job\"\n"
"ATTR mimeMediaType document-format application/pdf\n"
"ATTR octetString job-password \"password\"\n"
"ATTR keyword job-password-encryption none\n"
"\n"
"GROUP job-attributes-tag\n"
"ATTR integer copies 42\n"
"ATTR keyword job-hold-until indefinite\n"
"ATTR rangeOfInteger page-ranges 1-4,11-12\n"
"ATTR collection media-col {\n"
"    MEMBER collection media-size {\n"
"        MEMBER integer x-dimension $width\n"
"        MEMBER integer y-dimension $length\n"
"    }\n"
"    MEMBER keyword media-color $color\n"
"}\n"
"ATTR boolean agreement true\n"
"ATTR boolean disagreement false\n"
"\n"
"TEST";