const char testconfstr[] =
"ATTR boolean color-supported true\n"
"ATTR integer copies-default 1\n"
"ATTR rangeOfInteger copies-supported 1-999\n"
"ATTR mimeMediaType document-format-default application/octet-stream\n"
"ATTR mimeMediaType document-format-supported application/pdf,image/jpeg,image/pwg-raster,image/urf,application/octet-stream\n"
"\n"
"ATTR no-value finishings-col-default\n"
"ATTR collection finishings-col-database {\n"
"    MEMBER keyword finishing-template none\n"
"},\n"
"{\n"
"    MEMBER keyword finishing-template punch\n"
"},\n"
"{\n"
"    MEMBER keyword finishing-template punch-dual-top\n"
"},\n"
"{\n"
"    MEMBER keyword finishing-template punch-triple-left\n"
"},\n"
"{\n"
"    MEMBER keyword finishing-template staple\n"
"},\n"
"{\n"
"    MEMBER keyword finishing-template staple-top-left\n"
"},\n"
"{\n"
"    MEMBER keyword finishing-template staple-top-right\n"
"}\n"
"ATTR collection finishings-col-ready {\n"
"    MEMBER keyword finishing-template none\n"
"},\n"
"{\n"
"    MEMBER keyword finishing-template punch\n"
"},\n"
"{\n"
"    MEMBER keyword finishing-template punch-dual-top\n"
"},\n"
"{\n"
"    MEMBER keyword finishing-template punch-triple-left\n"
"},\n"
"{\n"
"    MEMBER keyword finishing-template staple\n"
"},\n"
"{\n"
"    MEMBER keyword finishing-template staple-top-left\n"
"},\n"
"{\n"
"    MEMBER keyword finishing-template staple-top-right\n"
"}\n"
"ATTR keyword finishings-col-supported finishing-template,punching,stitching\n"
"ATTR enum finishings-default 3\n"
"ATTR enum finishings-ready 3,4,5,20,22,75,78\n"
"ATTR enum finishings-supported 3,4,5,20,22,75,78\n"
"ATTR keyword finishing-template-supported none,punch,punch-dual-top,punch-triple-left,staple,staple-top-left,staple-top-right\n"
"ATTR octetString printer-finisher \"index=1;type=puncher;unit=sheets;maxcapacity=20;presentonoff=on;status=0;\",\"index=2;type=stitcher;unit=sheets;maxcapacity=20;presentonoff=on;status=0;\"\n"
"ATTR text printer-finisher-description \"Puncher SN:1234\",\"Stitcher SN:5678\"\n"
"ATTR rangeOfInteger punching-locations-supported 635-29065\n"
"ATTR integer punching-offset-supported 635\n"
"ATTR keyword punching-reference-edge-supported left,top\n"
"ATTR integer stitching-angle-supported 0,45,90\n"
"ATTR rangeOfInteger stitching-locations-supported 635-29065\n"
"ATTR keyword stitching-method-supported auto,crimp,wire\n"
"ATTR integer stitching-offset-supported 635\n"
"ATTR keyword stitching-reference-edge-supported left,right,top\n"
"\n"
"ATTR integer max-page-ranges-supported 1\n"
"\n"
"ATTR integer media-bottom-margin-supported 0,423\n"
"ATTR collection media-col-database {\n"
"    MEMBER collection media-size {\n"
"        MEMBER integer x-dimension 21590\n"
"        MEMBER integer y-dimension 27940\n"
"    }\n"
"},\n"
"{\n"
"    MEMBER collection media-size {\n"
"        MEMBER integer x-dimension 21000\n"
"        MEMBER integer y-dimension 29700\n"
"    }\n"
"},\n"
"{\n"
"    MEMBER collection media-size {\n"
"        MEMBER rangeOfInteger x-dimension 7620-21590\n"
"        MEMBER rangeOfInteger y-dimension 12700-29700\n"
"    }\n"
"    MEMBER keyword media-source manual\n"
"},\n"
"{\n"
"    MEMBER collection media-size {\n"
"        MEMBER rangeOfInteger x-dimension 7620-21590\n"
"        MEMBER rangeOfInteger y-dimension 12700-29700\n"
"    }\n"
"    MEMBER keyword media-source by-pass-tray\n"
"}\n"
"ATTR collection media-col-default {\n"
"    MEMBER integer media-bottom-margin 423\n"
"    MEMBER integer media-left-margin 423\n"
"    MEMBER integer media-right-margin 423\n"
"    MEMBER collection media-size {\n"
"        MEMBER integer x-dimension 21590\n"
"        MEMBER integer y-dimension 27940\n"
"    }\n"
"    MEMBER keyword media-source main\n"
"    MEMBER integer media-top-margin 423\n"
"    MEMBER keyword media-type stationery\n"
"}\n"
"ATTR collection media-col-ready {\n"
"    MEMBER integer media-bottom-margin 423\n"
"    MEMBER integer media-left-margin 423\n"
"    MEMBER integer media-right-margin 423\n"
"    MEMBER collection media-size {\n"
"        MEMBER integer x-dimension 21590\n"
"        MEMBER integer y-dimension 27940\n"
"    }\n"
"    MEMBER keyword media-source main\n"
"    MEMBER integer media-top-margin 423\n"
"    MEMBER keyword media-type stationery\n"
"},\n"
"{\n"
"    MEMBER integer media-bottom-margin 423\n"
"    MEMBER integer media-left-margin 423\n"
"    MEMBER integer media-right-margin 423\n"
"    MEMBER collection media-size {\n"
"        MEMBER integer x-dimension 21000\n"
"        MEMBER integer y-dimension 29700\n"
"    }\n"
"    MEMBER keyword media-source alternate\n"
"    MEMBER integer media-top-margin 423\n"
"    MEMBER keyword media-type stationery\n"
"}\n"
"ATTR keyword media-col-supported media-bottom-margin,media-left-margin,media-right-margin,media-size,media-size-name,media-source,media-top-margin,media-type\n"
"ATTR keyword media-default na_letter_8.5x11in\n"
"ATTR integer media-left-margin-supported 0,423\n"
"ATTR keyword media-ready na_letter_8.5x11in,iso_a4_210x297mm\n"
"ATTR integer media-right-margin-supported 0,423\n"
"ATTR collection media-size-supported {\n"
"    MEMBER integer x-dimension 21590\n"
"    MEMBER integer y-dimension 27940\n"
"},\n"
"{\n"
"    MEMBER integer x-dimension 21000\n"
"    MEMBER integer y-dimension 29700\n"
"},\n"
"{\n"
"    MEMBER rangeOfInteger x-dimension 7620-21590\n"
"    MEMBER rangeOfInteger y-dimension 12700-29700\n"
"}\n"
"ATTR keyword media-source-supported main,alternate,manual,by-pass-tray\n"
"ATTR keyword media-supported na_letter_8.5x11in,na_legal_8.5x14in,iso_a4_210x297mm,custom_min_3x5in,custom_max_8.5x14in\n"
"ATTR integer media-top-margin-supported 0,423\n"
"ATTR keyword media-type-supported stationery,stationery-letterhead\n"
"\n"
"ATTR enum orientation-requested-default 3\n"
"ATTR enum orientation-requested-supported 3,4,5,6,7\n"
"\n"
"ATTR keyword output-bin-default face-down\n"
"ATTR keyword output-bin-supported face-down\n"
"\n"
"ATTR keyword overrides-supported document-numbers,media,media-col,pages\n"
"\n"
"ATTR boolean page-ranges-supported true\n"
"\n"
"ATTR integer pages-per-minute 20\n"
"ATTR integer pages-per-minute-color 10\n"
"\n"
"ATTR keyword print-color-mode-default auto\n"
"ATTR keyword print-color-mode-supported auto,color,monochrome\n"
"\n"
"ATTR keyword print-content-optimize-default auto\n"
"ATTR keyword print-content-optimize-supported auto,graphic,photo,text,text-and-graphic\n"
"\n"
"ATTR enum print-quality-default 4\n"
"ATTR enum print-quality-supported 3,4,5\n"
"\n"
"ATTR text printer-make-and-model \"Test Printer\"\n"
"\n"
"ATTR resolution printer-resolution-default 600dpi\n"
"ATTR resolution printer-resolution-supported 300dpi,600dpi,1200x600dpi\n"
"\n"
"ATTR keyword sides-default one-sided\n"
"ATTR keyword sides-supported one-sided,two-sided-long-edge,two-sided-short-edge\n";